' CONFIG ----------------------------------------------------------------------
!$THEME_TEXT_COLOR = "#16160e"
!$THEME_BACKGROUND_COLOR = "#f7fcfe"
!$THEME_BACKGROUND_ACCENT_COLOR = "#fdeff2"
!$THEME_BORDER_COLOR = "#595455"
!$THEME_BORDER_THICKNESS = 2
'------------------------------------------------------------------------------

' skinparam BackgroundColor 
skinparam BoxPadding 15
' skinparam ColorArrowSeparationSpace
' skinparam ConditionStyle
' skinparam Dpi
' skinparam GenericDisplay
skinparam Guillemet true
' skinparam Handwritten
' skinparam HyperlineColor
' skinparam HyperlineUnderline
skinparam Linetype ortho
' skinparam MaxAsciiMessageLength
' skinparam MaxMessageSize
' skinparam MinClassWidth
' skinparam Monochrome
' skinparam Nodesep
skinparam Padding 5
' skinparam PathHoverColor
' skinparam Ranksep
skinparam ResponseMessageBelowArrow true
' skinparam RoundCorner
' skinparam SameClassWidth
skinparam Shadowing false
' skinparam Style
' skinparam SvglinkTarget
' skinparam TabSize
' skinparam WrapWidth
skinparam Default {
    FontColor $THEME_TEXT_COLOR
    ' FontName
    ' FontSize
    ' FontStyle
    ' MonospacedFontName
    TextAlignment center
}


skinparam Activity {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BarColor $THEME_BORDER_COLOR
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    DiamondBackgroundColor $THEME_BACKGROUND_ACCENT_COLOR
    DiamondBorderColor $THEME_BORDER_COLOR
    ' DiamondFontColor
    ' DiamondFontName
    ' DiamondFontSize
    DiamondFontStyle italic
    EndColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    StartColor $THEME_BORDER_COLOR
}
skinparam Actor {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Agent {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Arrow {
    Color $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' LollipopColor 
    MessageAlignment center
    Thickness $THEME_BORDER_THICKNESS
}
skinparam Artifact {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BarColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Biddable {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
}
skinparam Boundary {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Caption {
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
}
skinparam Card {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam CircledCharacter {
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' Radius
}
skinparam Class {
    ' AttributeFontColor
    ' AttributeFontName
    ' AttributeFontSize
    ' AttributeFontStyle
    ' AttributeIconSize
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' HeaderBackgroundColor
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Cloud {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Collections {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
}
skinparam Component {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
    ' Style
}
skinparam Control {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Database {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Designed {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
}
skinparam DesignedDomain {
    BorderThickness $THEME_BORDER_THICKNESS
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Diagram {
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
}
skinparam Domain {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Entity {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam File {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Folder {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Footer {
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
}
skinparam Frame {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Header {
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
}
skinparam Icon {
    ' IEMandatoryColor
    ' PackageBackgroundColor
    ' PackageColor
    ' PrivateBackgroundColor
    ' PrivateColor
    ' ProtectedBackgroundColor
    ' ProtectedColor
    ' PublicBackgroundColor
    ' PublicColor
}
skinparam Interface {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Legend {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
}
skinparam Lexical {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
}
skinparam Machine {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Node {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Note {
    BackgroundColor #fef263
    BorderColor $THEME_BORDER_COLOR
    BorderThickness 0.5
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    Shadowing true
    TextAlignment center
}
skinparam Object {
    ' AttributeFontColor
    ' AttributeFontName
    ' AttributeFontSize
    ' AttributeFontStyle
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Package {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
    ' Style
    ' TitleAlignment
}
skinparam Page {
    BorderColor $THEME_BORDER_COLOR
    ' ExternalColor
    ' Margin
}
skinparam Participant {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' Padding
}
skinparam Partition {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
}
skinparam Queue {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Rectangle {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Requirement {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam sequence {
    ActorBorderThickness $THEME_BORDER_THICKNESS
    ArrowThickness $THEME_BORDER_THICKNESS
    BoxBackgroundColor $THEME_BACKGROUND_COLOR
    BoxBorderColor $THEME_BORDER_COLOR
    ' BoxFontColor
    ' BoxFontName
    ' BoxFontSize
    ' BoxFontStyle
    ' DelayFontColor
    ' DelayFontName
    ' DelayFontSize
    ' DelayFontStyle
    DividerBackgroundColor $THEME_BACKGROUND_COLOR
    DividerBorderColor $THEME_BORDER_COLOR
    DividerBorderThickness $THEME_BORDER_THICKNESS
    ' DividerFontColor
    ' DividerFontName
    ' DividerFontSize
    ' DividerFontStyle
    GroupBackgroundColor $THEME_BACKGROUND_COLOR
    GroupBodyBackgroundColor $THEME_BACKGROUND_COLOR
    GroupBorderColor $THEME_BORDER_COLOR
    GroupBorderThickness $THEME_BORDER_THICKNESS
    ' GroupFontColor
    ' GroupFontName
    ' GroupFontSize
    ' GroupFontStyle
    ' GroupHeaderFontColor
    ' GroupHeaderFontName
    ' GroupHeaderFontSize
    ' GroupHeaderFontStyle
    LifeLineBackgroundColor $THEME_BACKGROUND_COLOR
    LifeLineBorderColor $THEME_BORDER_COLOR
    LifeLineBorderThickness $THEME_BORDER_THICKNESS
    MessageAlignment direction
    ' MessageTextAlignment
    ' NewpageSeparatorColor
    ' Participant
    ' ParticipantBorderThickness
    ' ReferenceAlignment
    ReferenceBackgroundColor $THEME_BACKGROUND_COLOR
    ReferenceBorderColor $THEME_BORDER_COLOR
    ReferenceBorderThickness $THEME_BORDER_THICKNESS
    ' ReferenceFontColor
    ' ReferenceFontName
    ' ReferenceFontSize
    ' ReferenceFontStyle
    ReferenceHeaderBackgroundColor $THEME_BACKGROUND_COLOR
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
    ' TitleFontColor
    ' TitleFontName
    ' TitleFontSize
    ' TitleFontStyle
}
skinparam Stack {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam State {
    ' AttributeFontColor
    ' AttributeFontName
    ' AttributeFontSize
    ' AttributeFontStyle
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    EndColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    StartColor $THEME_BORDER_COLOR
}
skinparam Stereotype {
    ABackgroundColor $THEME_BACKGROUND_COLOR
    ABorderColor $THEME_BORDER_COLOR
    CBackgroundColor $THEME_BACKGROUND_COLOR
    CBorderColor $THEME_BORDER_COLOR
    EBackgroundColor $THEME_BACKGROUND_COLOR
    EBorderColor $THEME_BORDER_COLOR
    IBackgroundColor $THEME_BACKGROUND_COLOR
    IBorderColor $THEME_BORDER_COLOR
    NBackgroundColor $THEME_BACKGROUND_COLOR
    NBorderColor $THEME_BORDER_COLOR
    ' Position 
}
skinparam Storage {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
skinparam Swimlane {
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    ' TitleFontColor
    ' TitleFontName
    ' TitleFontSize
    ' TitleFontStyle
    ' Width
    ' WrapTitleWidth
}
skinparam Title {
    ' BackgroundColor
    ' BorderColor
    ' BorderRoundCorner
    ' BorderThickness
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
}
skinparam Usecase {
    BackgroundColor $THEME_BACKGROUND_COLOR
    BorderColor $THEME_BORDER_COLOR
    BorderThickness $THEME_BORDER_THICKNESS
    ' FontColor
    ' FontName
    ' FontSize
    ' FontStyle
    ' StereotypeFontColor
    ' StereotypeFontName
    ' StereotypeFontSize
    ' StereotypeFontStyle
}
